// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, provider_id, account_id, access_token, refresh_token, password_hash, access_token_expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (provider_id, account_id) DO UPDATE SET
    access_token = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    access_token_expires_at = EXCLUDED.access_token_expires_at
RETURNING id, user_id, account_id, provider_id, access_token, refresh_token, access_token_expires_at, password_hash, created_at, updated_at
`

type CreateAccountParams struct {
	UserID               pgtype.UUID
	ProviderID           string
	AccountID            string
	AccessToken          pgtype.Text
	RefreshToken         pgtype.Text
	PasswordHash         pgtype.Text
	AccessTokenExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.ProviderID,
		arg.AccountID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.PasswordHash,
		arg.AccessTokenExpiresAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByProvider = `-- name: GetAccountByProvider :one
SELECT id, user_id, account_id, provider_id, access_token, refresh_token, access_token_expires_at, password_hash, created_at, updated_at FROM accounts
WHERE provider_id = $1
AND account_id = $2
`

type GetAccountByProviderParams struct {
	ProviderID string
	AccountID  string
}

func (q *Queries) GetAccountByProvider(ctx context.Context, arg GetAccountByProviderParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByProvider, arg.ProviderID, arg.AccountID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.ProviderID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessTokenExpiresAt,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
