// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkCommentExists = `-- name: CheckCommentExists :one
SELECT EXISTS (
    SELECT 1 FROM comments
    WHERE id = $1
)
`

func (q *Queries) CheckCommentExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkCommentExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createComment = `-- name: CreateComment :exec
INSERT INTO comments (
    content,
    author_id,
    feed_id,
    parent_id
)
VALUES ($1, $2, $3, $4)
`

type CreateCommentParams struct {
	Content  string
	AuthorID pgtype.UUID
	FeedID   pgtype.UUID
	ParentID pgtype.UUID
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.Exec(ctx, createComment,
		arg.Content,
		arg.AuthorID,
		arg.FeedID,
		arg.ParentID,
	)
	return err
}

const feedComments = `-- name: FeedComments :many
SELECT
    c.id,
    c.parent_id,
    c.feed_id,
    c.created_at,
    c.content,
    u.avatar_url,
    u.fullname,
    u.username,
    (SELECT COUNT(*) FROM likes l WHERE l.comment_id = c.id) AS like_count,
    EXISTS (
        SELECT 1 FROM likes l 
        WHERE l.comment_id = c.id
        AND l.user_id = $1::uuid
        AND entity_type = 'comment'
    ) AS is_liked
FROM comments c
LEFT JOIN users u ON u.id = c.author_id
WHERE c.feed_id = $2
AND (
    $3::TIMESTAMPTZ IS NULL
    OR $4::UUID IS NULL
    OR c.created_at < $3::TIMESTAMPTZ
    OR (c.created_at = $3::TIMESTAMPTZ AND c.id < $4::UUID)
)
ORDER BY c.created_at DESC, c.id DESC
LIMIT $5
`

type FeedCommentsParams struct {
	ViewerID   pgtype.UUID
	FeedID     pgtype.UUID
	CursorDate pgtype.Timestamptz
	CursorID   pgtype.UUID
	LimitCount int32
}

type FeedCommentsRow struct {
	ID        pgtype.UUID
	ParentID  pgtype.UUID
	FeedID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Content   string
	AvatarUrl pgtype.Text
	Fullname  pgtype.Text
	Username  pgtype.Text
	LikeCount int64
	IsLiked   bool
}

func (q *Queries) FeedComments(ctx context.Context, arg FeedCommentsParams) ([]FeedCommentsRow, error) {
	rows, err := q.db.Query(ctx, feedComments,
		arg.ViewerID,
		arg.FeedID,
		arg.CursorDate,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedCommentsRow
	for rows.Next() {
		var i FeedCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.FeedID,
			&i.CreatedAt,
			&i.Content,
			&i.AvatarUrl,
			&i.Fullname,
			&i.Username,
			&i.LikeCount,
			&i.IsLiked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, author_id, feed_id, parent_id, content, created_at, updated_at
FROM comments
WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id pgtype.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.FeedID,
		&i.ParentID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedCommentByID = `-- name: GetFeedCommentByID :one
SELECT
    c.id,
    c.parent_id,
    c.feed_id,
    c.content,
    c.created_at,
    u.fullname,
    u.username,
    u.avatar_url,
    (SELECT COUNT(*) FROM likes l WHERE l.comment_id = c.id) AS like_count,
    EXISTS (
        SELECT 1 FROM likes l 
        WHERE l.comment_id = c.id 
        AND l.user_id = $1::uuid
    ) AS is_liked
FROM comments c
LEFT JOIN users u ON u.id = c.author_id
WHERE c.id = $2
`

type GetFeedCommentByIDParams struct {
	ViewerID pgtype.UUID
	ID       pgtype.UUID
}

type GetFeedCommentByIDRow struct {
	ID        pgtype.UUID
	ParentID  pgtype.UUID
	FeedID    pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamptz
	Fullname  pgtype.Text
	Username  pgtype.Text
	AvatarUrl pgtype.Text
	LikeCount int64
	IsLiked   bool
}

func (q *Queries) GetFeedCommentByID(ctx context.Context, arg GetFeedCommentByIDParams) (GetFeedCommentByIDRow, error) {
	row := q.db.QueryRow(ctx, getFeedCommentByID, arg.ViewerID, arg.ID)
	var i GetFeedCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.FeedID,
		&i.Content,
		&i.CreatedAt,
		&i.Fullname,
		&i.Username,
		&i.AvatarUrl,
		&i.LikeCount,
		&i.IsLiked,
	)
	return i, err
}
