// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkFeedExists = `-- name: CheckFeedExists :one
SELECT EXISTS (
    SELECT 1 FROM feeds
    WHERE id = $1
)
`

func (q *Queries) CheckFeedExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkFeedExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createFeed = `-- name: CreateFeed :exec
INSERT INTO feeds (
    user_id,
    title,
    content,
    feed_image
) 
VALUES ($1, $2, $3, $4)
`

type CreateFeedParams struct {
	UserID    pgtype.UUID
	Title     string
	Content   pgtype.Text
	FeedImage pgtype.Text
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) error {
	_, err := q.db.Exec(ctx, createFeed,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.FeedImage,
	)
	return err
}

const feedDetails = `-- name: FeedDetails :one
SELECT 
  f.id,
  f.created_at,
  f.title,
  f.content,
  f.feed_image,
  u.avatar_url,
  u.fullname,
  u.username,
  (SELECT COUNT(*) FROM likes l WHERE l.feed_id = f.id) AS like_count,
  (SELECT COUNT(*) FROM comments c WHERE c.feed_id = f.id) AS comment_count,
  EXISTS (
      SELECT 1 FROM likes l 
      WHERE l.feed_id = f.id 
      AND l.user_id = $1
      AND l.entity_type = 'feed'
  ) AS is_liked
FROM feeds f
LEFT JOIN users u ON u.id = f.user_id
WHERE f.id = $2
`

type FeedDetailsParams struct {
	ViewerID pgtype.UUID
	ID       pgtype.UUID
}

type FeedDetailsRow struct {
	ID           pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	Title        string
	Content      pgtype.Text
	FeedImage    pgtype.Text
	AvatarUrl    pgtype.Text
	Fullname     pgtype.Text
	Username     pgtype.Text
	LikeCount    int64
	CommentCount int64
	IsLiked      bool
}

func (q *Queries) FeedDetails(ctx context.Context, arg FeedDetailsParams) (FeedDetailsRow, error) {
	row := q.db.QueryRow(ctx, feedDetails, arg.ViewerID, arg.ID)
	var i FeedDetailsRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Title,
		&i.Content,
		&i.FeedImage,
		&i.AvatarUrl,
		&i.Fullname,
		&i.Username,
		&i.LikeCount,
		&i.CommentCount,
		&i.IsLiked,
	)
	return i, err
}

const getFeeds = `-- name: GetFeeds :many
SELECT 
    f.id,
    f.title,
    f.content,
    f.feed_image,
    u.fullname,
    u.username,
    u.avatar_url,
    (SELECT COUNT(*) FROM likes l WHERE l.feed_id = f.id) AS like_count,
    (SELECT COUNT(*) FROM comments c WHERE c.feed_id = f.id) AS comment_count,
    EXISTS (
        SELECT 1 FROM likes l 
        WHERE l.feed_id = f.id 
        AND l.user_id = $1::uuid
        AND l.entity_type = 'feed'
    ) AS is_liked,
    f.created_at
FROM feeds f
LEFT JOIN users u ON u.id = f.user_id
WHERE
    (
        ($2::timestamptz IS NULL 
         OR $3::uuid IS NULL)
        OR (
            f.created_at < $2::timestamptz
            OR (
                f.created_at = $2::timestamptz 
                AND f.id < $3::uuid
            )
        )
    )
ORDER BY f.created_at DESC, f.id DESC
LIMIT $4
`

type GetFeedsParams struct {
	ViewerID   pgtype.UUID
	CursorDate pgtype.Timestamptz
	CursorID   pgtype.UUID
	Limit      int32
}

type GetFeedsRow struct {
	ID           pgtype.UUID
	Title        string
	Content      pgtype.Text
	FeedImage    pgtype.Text
	Fullname     pgtype.Text
	Username     pgtype.Text
	AvatarUrl    pgtype.Text
	LikeCount    int64
	CommentCount int64
	IsLiked      bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetFeeds(ctx context.Context, arg GetFeedsParams) ([]GetFeedsRow, error) {
	rows, err := q.db.Query(ctx, getFeeds,
		arg.ViewerID,
		arg.CursorDate,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedsRow
	for rows.Next() {
		var i GetFeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.FeedImage,
			&i.Fullname,
			&i.Username,
			&i.AvatarUrl,
			&i.LikeCount,
			&i.CommentCount,
			&i.IsLiked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
