// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: likes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commentLikeExists = `-- name: CommentLikeExists :one
SELECT EXISTS (
    SELECT 1 FROM likes
    WHERE user_id = $1
    AND comment_id = $2
    AND entity_type = 'comment'
)
`

type CommentLikeExistsParams struct {
	UserID    pgtype.UUID
	CommentID pgtype.UUID
}

func (q *Queries) CommentLikeExists(ctx context.Context, arg CommentLikeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, commentLikeExists, arg.UserID, arg.CommentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCommentLike = `-- name: CreateCommentLike :exec
INSERT INTO likes  
(user_id, comment_id, entity_type)
VALUES ($1, $2, 'comment')
`

type CreateCommentLikeParams struct {
	UserID    pgtype.UUID
	CommentID pgtype.UUID
}

func (q *Queries) CreateCommentLike(ctx context.Context, arg CreateCommentLikeParams) error {
	_, err := q.db.Exec(ctx, createCommentLike, arg.UserID, arg.CommentID)
	return err
}

const createFeedLike = `-- name: CreateFeedLike :exec
INSERT INTO likes  
(user_id, feed_id, entity_type)
VALUES ($1, $2, 'feed')
`

type CreateFeedLikeParams struct {
	UserID pgtype.UUID
	FeedID pgtype.UUID
}

func (q *Queries) CreateFeedLike(ctx context.Context, arg CreateFeedLikeParams) error {
	_, err := q.db.Exec(ctx, createFeedLike, arg.UserID, arg.FeedID)
	return err
}

const deleteCommentLike = `-- name: DeleteCommentLike :exec
DELETE FROM likes
WHERE user_id = $1
AND comment_id = $2
AND entity_type = 'comment'
`

type DeleteCommentLikeParams struct {
	UserID    pgtype.UUID
	CommentID pgtype.UUID
}

func (q *Queries) DeleteCommentLike(ctx context.Context, arg DeleteCommentLikeParams) error {
	_, err := q.db.Exec(ctx, deleteCommentLike, arg.UserID, arg.CommentID)
	return err
}

const deleteFeedLike = `-- name: DeleteFeedLike :exec
DELETE FROM likes
WHERE user_id = $1
AND feed_id = $2
AND entity_type = 'feed'
`

type DeleteFeedLikeParams struct {
	UserID pgtype.UUID
	FeedID pgtype.UUID
}

func (q *Queries) DeleteFeedLike(ctx context.Context, arg DeleteFeedLikeParams) error {
	_, err := q.db.Exec(ctx, deleteFeedLike, arg.UserID, arg.FeedID)
	return err
}

const feedLikeExists = `-- name: FeedLikeExists :one
SELECT EXISTS (
    SELECT 1 FROM likes
    WHERE user_id = $1
    AND feed_id = $2
    AND entity_type = 'feed'
)
`

type FeedLikeExistsParams struct {
	UserID pgtype.UUID
	FeedID pgtype.UUID
}

func (q *Queries) FeedLikeExists(ctx context.Context, arg FeedLikeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, feedLikeExists, arg.UserID, arg.FeedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
