// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	AccountID            string
	ProviderID           string
	AccessToken          pgtype.Text
	RefreshToken         pgtype.Text
	AccessTokenExpiresAt pgtype.Timestamptz
	PasswordHash         pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type Comment struct {
	ID        pgtype.UUID
	AuthorID  pgtype.UUID
	FeedID    pgtype.UUID
	ParentID  pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Feed struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	Content   pgtype.Text
	FeedImage pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Like struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	FeedID     pgtype.UUID
	CommentID  pgtype.UUID
	EntityType string
	CreatedAt  pgtype.Timestamptz
}

type Session struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Token     string
	IpAddress pgtype.Text
	UserAgent pgtype.Text
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	Email         string
	Fullname      string
	Username      string
	Bio           pgtype.Text
	EmailVerified bool
	AvatarUrl     pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
