// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserProfileByUsername = `-- name: GetUserProfileByUsername :one
SELECT
    u.id,
    u.fullname,
    u.username,
    u.bio,
    u.avatar_url,
    (SELECT COUNT(*) FROM likes l WHERE l.user_id = u.id) AS like_count,
    (SELECT COUNT(*) FROM comments c WHERE c.author_id = u.id) AS comment_count,
    (SELECT COUNT(*) FROM feeds ca WHERE ca.user_id = u.id) AS feed_count
FROM users u
WHERE u.username = $1
`

type GetUserProfileByUsernameRow struct {
	ID           pgtype.UUID
	Fullname     string
	Username     string
	Bio          pgtype.Text
	AvatarUrl    pgtype.Text
	LikeCount    int64
	CommentCount int64
	FeedCount    int64
}

func (q *Queries) GetUserProfileByUsername(ctx context.Context, username string) (GetUserProfileByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserProfileByUsername, username)
	var i GetUserProfileByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Username,
		&i.Bio,
		&i.AvatarUrl,
		&i.LikeCount,
		&i.CommentCount,
		&i.FeedCount,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    fullname = $1,
    username = $2,
    bio = $3
WHERE id = $4
RETURNING id, email, fullname, username, bio, email_verified, avatar_url, created_at, updated_at
`

type UpdateUserProfileParams struct {
	Fullname string
	Username string
	Bio      pgtype.Text
	ID       pgtype.UUID
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.Fullname,
		arg.Username,
		arg.Bio,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Fullname,
		&i.Username,
		&i.Bio,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userActivity = `-- name: UserActivity :many
WITH activity AS (
    SELECT
        'feed'        AS type,
        f.id,
        f.title       AS title,
        f.content     AS content,
        f.feed_image  AS feed_image,
        ''::TEXT    AS comment_body,
        ''::TEXT    AS parent_feed_title,
        NULL::UUID    AS comment_feed_id,
        (SELECT COUNT(*) FROM likes l WHERE l.feed_id = f.id)       AS like_count,
        (SELECT COUNT(*) FROM comments c WHERE c.feed_id = f.id)  AS comment_count,
        EXISTS (
            SELECT 1 FROM likes l
            WHERE l.feed_id = f.id
            AND  l.user_id = $4::uuid
            AND entity_type = 'feed'
        ) AS is_liked,
        f.created_at
    FROM feeds f
    WHERE f.user_id = $5

    UNION ALL

    SELECT
        'comment'     AS type,
        c.id,
        ''::TEXT    AS title,
        ''::TEXT    AS content,
        ''::TEXT    AS feed_image,
        c.content    AS comment_body,
        f.title       AS parent_feed_title,
        c.feed_id    AS comment_feed_id,
        (SELECT COUNT(*) FROM likes l WHERE l.comment_id = c.id)   AS like_count,
        0::BIGINT  AS comment_count,
        EXISTS (
            SELECT 1 FROM likes l
            WHERE l.comment_id = c.id
            AND l.user_id = $4::uuid
            AND entity_type = 'comment'
        ) AS is_liked,
        c.created_at
    FROM comments c
    JOIN feeds f ON c.feed_id = f.id
    WHERE c.author_id = $5
)

SELECT type, id, title, content, feed_image, comment_body, parent_feed_title, comment_feed_id, like_count, comment_count, is_liked, created_at
FROM activity
WHERE (
    $1::TIMESTAMPTZ IS NULL
    OR $2::UUID IS NULL
    OR created_at < $1::TIMESTAMPTZ
    OR (created_at = $1::TIMESTAMPTZ AND id < $2::UUID)
)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type UserActivityParams struct {
	CursorDate pgtype.Timestamptz
	CursorID   pgtype.UUID
	Limit      int32
	ViewerID   pgtype.UUID
	UserID     pgtype.UUID
}

type UserActivityRow struct {
	Type            string
	ID              pgtype.UUID
	Title           string
	Content         pgtype.Text
	FeedImage       pgtype.Text
	CommentBody     string
	ParentFeedTitle string
	CommentFeedID   pgtype.UUID
	LikeCount       int64
	CommentCount    int64
	IsLiked         bool
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) UserActivity(ctx context.Context, arg UserActivityParams) ([]UserActivityRow, error) {
	rows, err := q.db.Query(ctx, userActivity,
		arg.CursorDate,
		arg.CursorID,
		arg.Limit,
		arg.ViewerID,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserActivityRow
	for rows.Next() {
		var i UserActivityRow
		if err := rows.Scan(
			&i.Type,
			&i.ID,
			&i.Title,
			&i.Content,
			&i.FeedImage,
			&i.CommentBody,
			&i.ParentFeedTitle,
			&i.CommentFeedID,
			&i.LikeCount,
			&i.CommentCount,
			&i.IsLiked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userComments = `-- name: UserComments :many
SELECT
    c.id,
    f.title,
    c.feed_id,
    c.content,
    c.created_at,
    (SELECT COUNT(*) FROM likes l WHERE l.comment_id = c.id) AS like_count,
    EXISTS (
        SELECT 1 FROM likes l
        WHERE l.comment_id = c.id
        AND l.user_id = $1::uuid
    ) AS is_liked
FROM comments c
LEFT JOIN feeds f ON f.id = c.feed_id
WHERE c.author_id = $2
AND (
    $3::TIMESTAMPTZ IS NULL
    OR $4::UUID IS NULL
    OR c.created_at < $3::TIMESTAMPTZ
    OR (
        c.created_at = $3::TIMESTAMPTZ
        AND c.id < $4::UUID
    )
)
ORDER BY c.created_at DESC, c.id DESC
LIMIT $5
`

type UserCommentsParams struct {
	ViewerID   pgtype.UUID
	UserID     pgtype.UUID
	CursorDate pgtype.Timestamptz
	CursorID   pgtype.UUID
	Limit      int32
}

type UserCommentsRow struct {
	ID        pgtype.UUID
	Title     pgtype.Text
	FeedID    pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamptz
	LikeCount int64
	IsLiked   bool
}

func (q *Queries) UserComments(ctx context.Context, arg UserCommentsParams) ([]UserCommentsRow, error) {
	rows, err := q.db.Query(ctx, userComments,
		arg.ViewerID,
		arg.UserID,
		arg.CursorDate,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCommentsRow
	for rows.Next() {
		var i UserCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.FeedID,
			&i.Content,
			&i.CreatedAt,
			&i.LikeCount,
			&i.IsLiked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userFeeds = `-- name: UserFeeds :many
SELECT
    f.id,
    f.title,
    f.content,
    f.feed_image,
    (SELECT COUNT(*) FROM likes l WHERE l.feed_id = f.id) AS like_count,
    (SELECT COUNT(*) FROM comments c WHERE c.feed_id = f.id) AS comment_count,
    EXISTS (
        SELECT 1 FROM likes l
        WHERE l.feed_id = f.id
        AND l.user_id = $1::uuid
        AND l.entity_type = 'feed'
    ) AS is_liked,
    f.created_at
FROM feeds f
WHERE
    f.user_id = $2::uuid
    AND (
        ($3::timestamptz IS NULL
         OR $4::uuid IS NULL)
        OR (
            f.created_at < $3::timestamptz
            OR (
                f.created_at = $3::timestamptz
                AND f.id < $4::uuid
            )
        )
    )
ORDER BY f.created_at DESC, f.id DESC
LIMIT $5
`

type UserFeedsParams struct {
	ViewerID   pgtype.UUID
	UserID     pgtype.UUID
	CursorDate pgtype.Timestamptz
	CursorID   pgtype.UUID
	Limit      int32
}

type UserFeedsRow struct {
	ID           pgtype.UUID
	Title        string
	Content      pgtype.Text
	FeedImage    pgtype.Text
	LikeCount    int64
	CommentCount int64
	IsLiked      bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) UserFeeds(ctx context.Context, arg UserFeedsParams) ([]UserFeedsRow, error) {
	rows, err := q.db.Query(ctx, userFeeds,
		arg.ViewerID,
		arg.UserID,
		arg.CursorDate,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserFeedsRow
	for rows.Next() {
		var i UserFeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.FeedImage,
			&i.LikeCount,
			&i.CommentCount,
			&i.IsLiked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
