// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (fullname, email, username, avatar_url)
VALUES ($1, $2, $3, $4)
RETURNING id, email, fullname, username, bio, email_verified, avatar_url, created_at, updated_at
`

type CreateUserParams struct {
	Fullname  string
	Email     string
	Username  string
	AvatarUrl pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Fullname,
		arg.Email,
		arg.Username,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Fullname,
		&i.Username,
		&i.Bio,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, fullname, username, bio, email_verified, avatar_url, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Fullname,
		&i.Username,
		&i.Bio,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, fullname, username, bio, email_verified, avatar_url, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Fullname,
		&i.Username,
		&i.Bio,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByToken = `-- name: GetUserByToken :one
SELECT
    u.id,
    u.fullname,
    u.username,
    u.bio,
    u.avatar_url
FROM users u
JOIN sessions s ON s.user_id = u.id
WHERE s.token = $1
AND s.expires_at > NOW()
`

type GetUserByTokenRow struct {
	ID        pgtype.UUID
	Fullname  string
	Username  string
	Bio       pgtype.Text
	AvatarUrl pgtype.Text
}

func (q *Queries) GetUserByToken(ctx context.Context, token string) (GetUserByTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserByToken, token)
	var i GetUserByTokenRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Username,
		&i.Bio,
		&i.AvatarUrl,
	)
	return i, err
}

const getUserIDByUsername = `-- name: GetUserIDByUsername :one
SELECT id FROM users
WHERE username = $1
`

func (q *Queries) GetUserIDByUsername(ctx context.Context, username string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByUsername, username)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
