/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _protectedRouteRouteImport } from './routes/__protected/route'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as FeedsFeedIdRouteImport } from './routes/feeds/$feedId'
import { Route as ProfileUsernameRouteRouteImport } from './routes/profile/$username/route'
import { Route as ProfileUsernameIndexRouteImport } from './routes/profile/$username/index'
import { Route as _protectedCreateIndexRouteImport } from './routes/__protected/create/index'
import { Route as ProfileUsernamePostsRouteImport } from './routes/profile/$username/posts'
import { Route as ProfileUsernameCommentsRouteImport } from './routes/profile/$username/comments'

const _protectedRouteRoute = _protectedRouteRouteImport.update({
  id: '/__protected',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsFeedIdRoute = FeedsFeedIdRouteImport.update({
  id: '/feeds/$feedId',
  path: '/feeds/$feedId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRouteRoute = ProfileUsernameRouteRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameIndexRoute = ProfileUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const _protectedCreateIndexRoute = _protectedCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => _protectedRouteRoute,
} as any)
const ProfileUsernamePostsRoute = ProfileUsernamePostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)
const ProfileUsernameCommentsRoute = ProfileUsernameCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => ProfileUsernameRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/profile/$username': typeof ProfileUsernameRouteRouteWithChildren
  '/feeds/$feedId': typeof FeedsFeedIdRoute
  '/profile/$username/comments': typeof ProfileUsernameCommentsRoute
  '/profile/$username/posts': typeof ProfileUsernamePostsRoute
  '/create/': typeof _protectedCreateIndexRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeIndexRoute
  '/feeds/$feedId': typeof FeedsFeedIdRoute
  '/profile/$username/comments': typeof ProfileUsernameCommentsRoute
  '/profile/$username/posts': typeof ProfileUsernamePostsRoute
  '/create': typeof _protectedCreateIndexRoute
  '/profile/$username': typeof ProfileUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__protected': typeof _protectedRouteRouteWithChildren
  '/profile/$username': typeof ProfileUsernameRouteRouteWithChildren
  '/feeds/$feedId': typeof FeedsFeedIdRoute
  '/_home/': typeof HomeIndexRoute
  '/profile/$username/comments': typeof ProfileUsernameCommentsRoute
  '/profile/$username/posts': typeof ProfileUsernamePostsRoute
  '/__protected/create/': typeof _protectedCreateIndexRoute
  '/profile/$username/': typeof ProfileUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile/$username'
    | '/feeds/$feedId'
    | '/profile/$username/comments'
    | '/profile/$username/posts'
    | '/create/'
    | '/profile/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feeds/$feedId'
    | '/profile/$username/comments'
    | '/profile/$username/posts'
    | '/create'
    | '/profile/$username'
  id:
    | '__root__'
    | '/__protected'
    | '/profile/$username'
    | '/feeds/$feedId'
    | '/_home/'
    | '/profile/$username/comments'
    | '/profile/$username/posts'
    | '/__protected/create/'
    | '/profile/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _protectedRouteRoute: typeof _protectedRouteRouteWithChildren
  ProfileUsernameRouteRoute: typeof ProfileUsernameRouteRouteWithChildren
  FeedsFeedIdRoute: typeof FeedsFeedIdRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__protected': {
      id: '/__protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/$feedId': {
      id: '/feeds/$feedId'
      path: '/feeds/$feedId'
      fullPath: '/feeds/$feedId'
      preLoaderRoute: typeof FeedsFeedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username/': {
      id: '/profile/$username/'
      path: '/'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof ProfileUsernameIndexRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/__protected/create/': {
      id: '/__protected/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof _protectedCreateIndexRouteImport
      parentRoute: typeof _protectedRouteRoute
    }
    '/profile/$username/posts': {
      id: '/profile/$username/posts'
      path: '/posts'
      fullPath: '/profile/$username/posts'
      preLoaderRoute: typeof ProfileUsernamePostsRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
    '/profile/$username/comments': {
      id: '/profile/$username/comments'
      path: '/comments'
      fullPath: '/profile/$username/comments'
      preLoaderRoute: typeof ProfileUsernameCommentsRouteImport
      parentRoute: typeof ProfileUsernameRouteRoute
    }
  }
}

interface _protectedRouteRouteChildren {
  _protectedCreateIndexRoute: typeof _protectedCreateIndexRoute
}

const _protectedRouteRouteChildren: _protectedRouteRouteChildren = {
  _protectedCreateIndexRoute: _protectedCreateIndexRoute,
}

const _protectedRouteRouteWithChildren = _protectedRouteRoute._addFileChildren(
  _protectedRouteRouteChildren,
)

interface ProfileUsernameRouteRouteChildren {
  ProfileUsernameCommentsRoute: typeof ProfileUsernameCommentsRoute
  ProfileUsernamePostsRoute: typeof ProfileUsernamePostsRoute
  ProfileUsernameIndexRoute: typeof ProfileUsernameIndexRoute
}

const ProfileUsernameRouteRouteChildren: ProfileUsernameRouteRouteChildren = {
  ProfileUsernameCommentsRoute: ProfileUsernameCommentsRoute,
  ProfileUsernamePostsRoute: ProfileUsernamePostsRoute,
  ProfileUsernameIndexRoute: ProfileUsernameIndexRoute,
}

const ProfileUsernameRouteRouteWithChildren =
  ProfileUsernameRouteRoute._addFileChildren(ProfileUsernameRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  _protectedRouteRoute: _protectedRouteRouteWithChildren,
  ProfileUsernameRouteRoute: ProfileUsernameRouteRouteWithChildren,
  FeedsFeedIdRoute: FeedsFeedIdRoute,
  HomeIndexRoute: HomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
